version: '3'

services:
  db-web:
    build: tools/cassandra-web
    ports:
      - "8081:3000"
    environment:
      HOSTS: db1,db2,db3
    depends_on:
      - db1
      - db2
      - db3
  db1:
    image: scylladb/scylla
    command: --seeds=db1,db2
    ports:
      - "19042:9042"
    volumes:
      - ./db-volumes/1:/var/lib/scylla
  db2:
    image: scylladb/scylla
    command: --seeds=db1,db2
    depends_on:
      - db1
    volumes:
      - ./db-volumes/2:/var/lib/scylla
  db3:
    image: scylladb/scylla
    command: --seeds=db1,db2
    depends_on:
      - db1
    volumes:
      - ./db-volumes/3:/var/lib/scylla