version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: postgres-password
    volumes:
      - "./database/scripts:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/postgresql/data"

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_DATABASE: db
      DB_USER: postgres
      DB_PASSWORD: postgres-password
    depends_on:
      - db

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
