name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, synchronize, reopened, unlabeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
