name: Server validation

on:
  push:
    branches: [master]
    paths:
      - ./server
      - .github/workflows/server-validate.yml
  pull_request:
    branches: [master]
    paths:
      - ./server
      - .github/workflows/server-validate.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        working-directory: ./server
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
