name: Server validation

on:
  push:
    branches: [master]
    paths:
      - ./server/**
      - .github/workflows/server-validation.yml
  pull_request:
    branches: [master]
    paths:
      - ./server/**
      - .github/workflows/server-validation.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  validation:
    name: Server validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./server/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./server/Cargo.lock') }}
      - name: Build
        run: cargo build
        working-directory: ./server
      - name: Run tests
        run: cargo test
        working-directory: ./server
