name: Web validation

on:
  push:
    branches: [master]
    paths:
      - web/**
      - .github/workflows/web-validation.yml
  pull_request:
    branches: [master]
    paths:
      - web/**
      - .github/workflows/web-validation.yml

jobs:
  validation:
    name: Web validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: "./web/package-lock.json"
      - run: npm ci
        working-directory: ./web
      - run: npm run build
        working-directory: ./web
      - run: npm test
        working-directory: ./web
